1. Create a numpy array with numpy.array module and with a data type integer and float.


In [107]:
import numpy

In [108]:
a=numpy.array([1,2,3],dtype=int)

In [109]:
a.dtype

dtype('int64')

In [110]:
a=numpy.array([1,2,3],dtype=float)
a.dtype

dtype('float64')

Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.


In [111]:
import numpy as np
a=np.array(10)

In [112]:
# ndim --> check the dimension of array
a.ndim

0

In [113]:
a.shape

()

In [114]:
a=np.array([10])
print(a.ndim)
print(a.shape)

1
(1,)


In [115]:
a=np.array([10],ndmin=2)
print(a)
print(a.ndim)
print(a.shape)

[[10]]
2
(1, 1)


In [116]:
a=np.array([10],ndmin=3)
print(a)
print(a.ndim)
print(a.shape)

[[[10]]]
3
(1, 1, 1)


In [117]:
a=np.array([10],ndmin=4)
print(a)
print(a.ndim)
print(a.shape)

[[[[10]]]]
4
(1, 1, 1, 1)


In [118]:
a=np.array([[10]])
print(a)
print(a.ndim)
print(a.shape)

[[10]]
2
(1, 1)


3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.


In [119]:
np.identity(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [120]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [121]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [122]:
np.eye(2,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

4. Create a numpy array with shape 2x5 that has all the elements as zero.


In [123]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

5. Create a numpy array that has the shape 3x5 and all the elements are 5.


In [124]:
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [125]:
np.full((3, 5), 5, dtype=int)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.


In [126]:
np.random.randint(0,100,25)

array([43, 76, 22, 96, 20, 63, 59, 42, 78, 90, 84, 37, 84, 68, 60, 82, 69,
       44, 35, 83, 19, 28,  7, 45, 99])

In [127]:
print(np.random.randint(low=0, high=100, size=25))

[16  7 31 74 58 24 71 62 35 99 83 25 52 51 82 74 58 10 93 62 56 98 89 70
  9]


In [128]:
np.random.randint(100,size=25)

array([17, 51,  3, 89, 42, 35, 38, 64, 10, 99, 65, 57, 59, 60, 96, 79,  2,
       22, 94, 70, 99, 60, 75, 40, 32])

7. Create a numpy array with a shape 3x3 that has all elements as 1.


In [129]:
print(np.ones((3, 3), dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [130]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.


In [131]:
a=np.random.randint(100,size=(2,3))
a


array([[91, 80,  2],
       [77, 37, 22]])

In [132]:
a.reshape(3,2)

array([[91, 80],
       [ 2, 77],
       [37, 22]])

9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the
following operations on the same.
- Print the first ten elements of the array.
- Print the last ten elements of the array
- Print the elements from the indexes 10-25
- Print the element at the index 22
- Print the array using negative indexing.
- Print the last ten elements of the array, using negative indexing.


In [133]:
x=np.random.randint(1000,size=50)

In [134]:
x

array([550, 762, 612, 789, 408, 632, 610, 653, 466, 939,  56, 864, 531,
       125, 255, 428, 808, 219,  27, 114, 681, 620, 886, 473,  57, 621,
       672, 590, 603, 512, 200, 460,  59, 231, 436, 190, 452,   4, 532,
       209, 482, 391, 598, 546, 542, 596, 262, 992, 117, 754])

In [135]:
x[:5]

array([550, 762, 612, 789, 408])

In [136]:
x[45:51]

array([596, 262, 992, 117, 754])

In [137]:
x[10:26]

array([ 56, 864, 531, 125, 255, 428, 808, 219,  27, 114, 681, 620, 886,
       473,  57, 621])

In [138]:
x[22]

886

In [139]:
x[-50:]

array([550, 762, 612, 789, 408, 632, 610, 653, 466, 939,  56, 864, 531,
       125, 255, 428, 808, 219,  27, 114, 681, 620, 886, 473,  57, 621,
       672, 590, 603, 512, 200, 460,  59, 231, 436, 190, 452,   4, 532,
       209, 482, 391, 598, 546, 542, 596, 262, 992, 117, 754])

In [140]:
x[40:51]

array([482, 391, 598, 546, 542, 596, 262, 992, 117, 754])

In [141]:
x[-10:]

array([482, 391, 598, 546, 542, 596, 262, 992, 117, 754])

10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
-  Insert the element 6 at the end of the array.
-  Insert the element 10 at the beginning of the array.
-  Insert the element 30, before 4.
-  Update the element 5 as 50.
-  Delete the element 50 in the updated array.
-  Create a function to search for the element 30.
-  Sort the array in ascending order

In [159]:
a=np.array([1,2,3,4,5])

In [160]:
a=np.append(a,6)
a

array([1, 2, 3, 4, 5, 6])

Insert the element 10 at the beginning of the array.

In [161]:
a=np.insert(a,0,10)
a

array([10,  1,  2,  3,  4,  5,  6])

In [162]:
#a[0] = 10
#a

Insert the element 30, before 4.

In [163]:
np.insert(a,np.where(a==4)[0],30)


array([10,  1,  2,  3, 30,  4,  5,  6])

In [164]:
a=np.insert(a,4,30)
a

array([10,  1,  2,  3, 30,  4,  5,  6])

Update the element 5 as 50.

In [165]:
a[6]=50
a

array([10,  1,  2,  3, 30,  4, 50,  6])

- Delete the element 50 in the updated array.
- Create a function to search for the element 30.

In [166]:
a=np.delete(a,6)
a

array([10,  1,  2,  3, 30,  4,  6])

In [169]:
def abc(x,i):
    if i in x:
        print('30 found')
    else:
        print('30 not found')
abc(a,30)

30 found


Sort the array in ascending order

In [170]:
a.sort()

In [171]:
a

array([ 1,  2,  3,  4,  6, 10, 30])

## Hands on -2

Given two numpy arrays A and B that have values [1,2,3,4] and [5,6,7,8] respectively.
Perform the following operations.
-  Add the two arrays
-  Subtract the two arrays
-  Multiply the two arrays:
  -  With 5
  -  With each other.
-  Divide the two arrays:
  -  By 2
  -  Divide A with B
  -  Divide B with A

In [172]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [175]:
np.sum((a,b),axis=0)

array([ 6,  8, 10, 12])

In [176]:
np.sum((a,b))

36

In [177]:
np.subtract(a,b)

array([-4, -4, -4, -4])

Multiply the two arrays:


With 5,
With each other.

In [178]:
np.multiply(a,b*5)

array([ 25,  60, 105, 160])

In [179]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

Divide the two arrays:
- By 2
- Divide A with B
- Divide B with A

In [180]:
np.divide(a,b/2)

array([0.4       , 0.66666667, 0.85714286, 1.        ])

In [181]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [182]:
np.divide(b,a)

array([5.        , 3.        , 2.33333333, 2.        ])

For the given two arrays A and B.
- a = np.array([[2,9],[6,13]])
- b = np.array([[1,4],[3,11]])


Perform the following operations,
- Cross product of A and B.
-  Dot product of A and B.
-  Matrix multiplication of A and B.
- Square root of A and B

In [184]:
a = np.array([[2,9],[6,13]])
b = np.array([[1,4],[3,11]])
np.cross(a,b)

array([-1, 27])

In [185]:
np.dot(a,b)


array([[ 29, 107],
       [ 45, 167]])

In [186]:
np.multiply(a,b)


array([[  2,  36],
       [ 18, 143]])

In [188]:

np.sqrt(b)


array([[1.        , 2.        ],
       [1.73205081, 3.31662479]])

In [189]:
np.sqrt(a)

array([[1.41421356, 3.        ],
       [2.44948974, 3.60555128]])

In [190]:
np.sqrt(a*b)

array([[ 1.41421356,  6.        ],
       [ 4.24264069, 11.95826074]])

 Create a 3x3 matrix with random values, flatten the array with the reshape() method and
print the shape of the flattened array and the resultant array.


In [191]:
arr = np.random.random((3,3))
print(arr.shape)
arr = arr.reshape(-1)
print(arr.shape)

(3, 3)
(9,)


In [192]:

arr

array([0.57863778, 0.77220699, 0.49822984, 0.61768707, 0.98507367,
       0.28216138, 0.74558035, 0.58420275, 0.63297385])

In [193]:
a = np.arange(1,10,1).reshape(3,3)
b = a.reshape(1,9)
b.shape

(1, 9)

In [194]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

4. Create an array that will have days from an entire year in the datetime format using the
datetime64 numpy method.


In [196]:
a = np.datetime64('2023-01-01')
a
b = np.arange(a, a + np.timedelta64(365), np.timedelta64(1, 'D'))
b

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
       '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
       '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
       '2023-03-02', '2023-03-03', '2023-03-04', '2023-

In [197]:
dates = np.arange('2023-01','2024-01',dtype='datetime64[D]')

In [198]:
dates

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
       '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
       '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
       '2023-03-02', '2023-03-03', '2023-03-04', '2023-

In [199]:
arr = np.arange(np.datetime64("2000-01-01"), np.datetime64("2001-01-01"), np.timedelta64(1, "D"))
arr.shape


(366,)

5. Given two arrays A and B, perform the following operations
A = np.array([[2,3],[6,4]])
B = np.array([[3,6],[4,9]])
-  Horizontal stacking
-  Vertical Stacking
- Row Stacking
- Column Stacking
- Depth Stacking
- Append A to B
- Concatenate A and B


In [200]:
A = np.array([[2,3],[6,4]])
B = np.array([[3,6],[4,9]])

In [202]:
np.hstack([A,B])



array([[2, 3, 3, 6],
       [6, 4, 4, 9]])

In [203]:
np.vstack([A,B])


array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [204]:
np.row_stack([A,B])


array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [205]:
np.column_stack([A,B])

array([[2, 3, 3, 6],
       [6, 4, 4, 9]])

In [206]:
np.dstack((A,B))


array([[[2, 3],
        [3, 6]],

       [[6, 4],
        [4, 9]]])

In [207]:
np.concatenate((A,B))


array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [208]:
np.append(A,B)


array([2, 3, 6, 4, 3, 6, 4, 9])

In [211]:
print(numpy.hstack((A,B)))


[[2 3 3 6]
 [6 4 4 9]]


6. Given an array A, perform the following operations
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15], [16,17,18]])
-  Horizontal split
-  Vertical Split
-  Row Split
-  Column Split

In [221]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [220]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15], [16,17,18]])
np.hsplit(A,3)



[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [214]:
np.vsplit(A,3)


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [223]:
np.split(A,3,axis=0)


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [216]:
np.split(A,3,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

For a given 3x3 matrix, perform the following operations.
A = np.array([[1,4,7],[3,1,9],[2,8,11]])
-  Find the rank of the matrix
-  Find the trace of the matrix
-  Find the inverse of the matrix
-  Find the transpose of the matrix
-  Find the determinant of the matrix
-  Find the eigenvalues and eigenvectors the matrix


In [224]:
A = np.array([[1,4,7],[3,1,9],[2,8,11]])

In [225]:
np.linalg.matrix_rank(A)


3

In [226]:
A.trace()

13

In [227]:
np.linalg.inv(A)

array([[-1.84848485,  0.36363636,  0.87878788],
       [-0.45454545, -0.09090909,  0.36363636],
       [ 0.66666667,  0.        , -0.33333333]])

In [228]:
A.transpose()

array([[ 1,  3,  2],
       [ 4,  1,  8],
       [ 7,  9, 11]])

In [229]:
np.linalg.det(A)

33.000000000000014

In [230]:
np.linalg.eig(A)

(array([17.41535066, -0.48171173, -3.93363893]),
 array([[-0.44018011, -0.89954986,  0.05526996],
        [-0.49219026, -0.26902919, -0.88319891],
        [-0.75099282,  0.34414147,  0.46573052]]))

For the given two arrays A and B, find the correlation coefficients.
- A = np.array([[11,17,42],[21,19,27]])
- B = np.array([[12,44,39],[62,81,10]])

In [231]:
A = np.array([[11,17,42],[21,19,27]])
B = np.array([[12,44,39],[62,81,10]])

In [232]:
np.corrcoef(A,B)


array([[ 1.        ,  0.9106039 ,  0.53232532, -0.90264562],
       [ 0.9106039 ,  1.        ,  0.13487934, -0.99982205],
       [ 0.53232532,  0.13487934,  1.        , -0.11616343],
       [-0.90264562, -0.99982205, -0.11616343,  1.        ]])