## Doubts

In [3]:
# In java there is concept of singleton class. Is similar thing there in Python class?

In [2]:
# Can you please explain the Lambda function and in what scenerio will we use it
# lambda arguments : expression

In [1]:
add = lambda x,y : x+y
add(3,4)

7

In [5]:
user_input = input("enter five number")
elements  = user_input.split()
print("elements :",elements)

enter five number1 2 3 4 5
elements : ['1', '2', '3', '4', '5']


In [6]:
user_input = input("enter five number")
elements  = user_input.split(',')
print("elements :",elements)

enter five number1,2,3,4,5
elements : ['1', '2', '3', '4', '5']


In [7]:
user_input = input("enter five number")
elements  = user_input.split(':')
print("elements :",elements)

enter five number1:2:3:4:5
elements : ['1', '2', '3', '4', '5']


## Installing and Importing Numpy

In [8]:
pip install numpy

In [9]:
import numpy as np

## Create a Numpy Array (Ndarray)

In [10]:
np.array(11)  # 0 dimensional array

array(11)

In [12]:
np.array([1,2,3,4,5]) # 1 dimensional array

array([1, 2, 3, 4, 5])

In [14]:
np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2 dimensional arrays

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

## Array Initialization

### initialize all the elements of X * Y array to 0

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4) , dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### initialize all the elements to Ones

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(5 , int)

array([1, 1, 1, 1, 1])

### Initialize all the elements using full

In [19]:
np.full((2,5) , 6 , dtype=int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Arange function()

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
# even numbers between 10 and 20
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [24]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### random function

In [26]:
arr = np.random.random((2,3))

In [27]:
arr

array([[0.7079548 , 0.20188531, 0.4903584 ],
       [0.99535721, 0.7742605 , 0.19842787]])

In [28]:
type(arr)

numpy.ndarray

## Array Inspection

In [29]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [31]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr.shape

(2, 4)

In [33]:
arr = np.array([[2,3,4],[4,4,6]])
arr.shape

(2, 3)

In [34]:
arr.shape = (3,2)
arr

array([[2, 3],
       [4, 4],
       [4, 6]])

In [35]:
arr = np.array([[2,3,4,4],[2,4,4,6]])
arr.shape = (8,1)
arr

array([[2],
       [3],
       [4],
       [4],
       [2],
       [4],
       [4],
       [6]])

In [39]:
ar = np.arange(24)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
ar.ndim

1

In [48]:
ar = ar.reshape(12,2)

In [49]:
ar.ndim

2

In [43]:
arr = np.array([[2,3,4],[4,4,6]])

In [45]:
arr.ndim

2

In [55]:
arr.size

6

In [50]:
arr.dtype

dtype('int32')

In [51]:
a = np.zeros((3,4))

In [52]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
a.dtype

dtype('float64')

In [54]:
a.size

12

## Array mathematics

In [56]:
np.sum([10,20])

30

In [57]:
a,b = 10,20

In [58]:
np.sum([a,b])

30

In [60]:
np.sum([[1,2],[5,6]] , axis = 0)  # 5+1 , 2+6

array([6, 8])

axis = 0
6 8
- -
1 2  -> 3     axis = 1
5 6  -> 11

In [61]:
np.sum([[1,2],[5,6]] , axis = 1)

array([ 3, 11])

In [62]:
np.sum([[1,2],[5,6]])

14

In [63]:
np.subtract(10,20)

-10

In [64]:
np.multiply(2,3)

6

In [65]:
np.divide(10,5)

2.0

In [67]:
a = np.array([2,3,4])
b = np.array([1,2,3])
c = np.multiply(a,b)

In [70]:
a.ndim

1

In [68]:
c

array([ 2,  6, 12])

In [69]:
c.ndim

1

In [71]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        ])

In [72]:
print("SIn : ",np.sin(a))
print("Cos : ",np.cos(a))
print("Log : ",np.log(a))

SIn :  [ 0.90929743  0.14112001 -0.7568025 ]
Cos :  [-0.41614684 -0.9899925  -0.65364362]
Log :  [0.69314718 1.09861229 1.38629436]


### Array Comparison

In [75]:
a = [1,2,3]
b = [2,3,3]
c = [1,2,4]
np.equal(a,b)

array([False, False,  True])

In [77]:
np.equal(a,c)

array([ True,  True, False])

### Aggregate Function

In [88]:
a = [1,2,3]
b = [2,3,3]
c = [1,2,4]

print("Sum : ", np.sum(a))
print("Minimum : ",np.min(b))
print("Minimum : ",np.minimum(b , c))   # Compare two arrays and returns a new array containing the element-wise minima
print("Maximum : ",np.max(b))
print("Mean : ",np.mean(a))
print("median : ",np.median(b))
print("Standard Deviation : ",np.std(c))
print("variance : ",np.var(a))

Sum :  6
Minimum :  2
Minimum :  [1 2 3]
Maximum :  3
Mean :  2.0
median :  3.0
Standard Deviation :  1.247219128924647
variance :  0.6666666666666666


## Indexing and Slicing in Python

In [89]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
a[0]

array([1, 2, 3])

In [92]:
a[1]

array([4, 5, 6])

In [93]:
a[:1]

array([[1, 2, 3]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

         0  1  2
      0 [1, 2, 3],
      1 [4, 5, 6],
      2 [7, 8, 9]

In [95]:
# array[rows , cols]
a[:1 , 1:]   #a[0:0 , 1:2]   a[row 0 ,col 1 to 2 ]

array([[2, 3]])

In [97]:
a[0:2] # a[start , stop-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
a[:2 , 1:]   # a[rows , cols]  a[0:1 , 1:2]

array([[2, 3],
       [5, 6]])

         0  1  2
      0 [1, 2, 3],
      1 [4, 5, 6],
      2 [7, 8, 9]

In [100]:
a[1: , 1:]   # a[1:2 , 1:2]

array([[5, 6],
       [8, 9]])

In [101]:
np.random.randint(1 , 100 , size = (3,4))

array([[86, 66, 52, 47],
       [ 8, 80, 28, 59],
       [21, 23, 60, 63]])

## Array manipulation

In [104]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [105]:
# stack arrays row-wise - horizontal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [106]:
# stack arrays row-wise - vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# combining column wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
arr = np.arange(16).reshape(4,4)
print(arr , "\n")
print(np.hsplit(arr , 2))

print("\n\n")
print(np.hsplit(arr , np.array([2,3]))) 
#     0  1  2  3     
#  0[ 0  1  2  3]
#  1[ 4  5  6  7]
#  2[ 8  9 10 11]
#  3[12 13 14 15]



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]



[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


## Advantage of Numpy Array over list

In [144]:
my_list  = [1,2,3,4,5]
squared_list = [x**2 for x in my_list]
print(squared_list)

[1, 4, 9, 16, 25]


In [143]:
my_array = np.array([1,2,3,4,5])
# squared_array = my_array**2
squared_array = np.square(my_array)

# squared_array = np.sqrt()

print(squared_array)

[ 1  4  9 16 25]


In [138]:
import time
def using_list():
    t1 = time.time()
    X = range(10000)
    Y = range(10000)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def using_Numpy():
    t2 = time.time()
    A = np.arange(10000)
    B = np.arange(10000)
    C = a+b
    return time.time() - t2

list_time = using_list()
array_time = using_Numpy()

print(list_time,array_time)

print("Numpy is : "+str(list_time/array_time)+" times faster than list ")

0.0034961700439453125 0.00099945068359375
Numpy is : 3.4980916030534353 times faster than list 
