# Module 4 Numpy Case Study

In [1]:
import numpy as np

## Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value and returns a NumPy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
```python
[
[5, 5, 5],
[5, 5, 5],
[5, 5, 5]
]
```


In [2]:
def createArray(size, ele):
    return ele*np.ones(size)
createArray((3,3),5)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

## Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer.


In [4]:
def sumArray(*arrays):
    sumArray = np.zeros(arrays[0].shape)
    for array in arrays:
        sumArray += array
    return sumArray
sumArray(np.arange(1,5),np.arange(6,10),np.arange(2,6),np.arange(3,7))

array([12., 16., 20., 24.])

## Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix, e.g:
```
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
```
top_left_sub_matrix (matrix, 2, 2) -> should return:
```
[
[1, 2]
[4, 5]
]
```


In [13]:
array = np.random.randint(1,10,(7,8))
print(f"array = {array}")
n = int(input("Enter n\t"))
m = int(input("Enter m\t"))
def top_left_sub_matrix(matrix, n, m):
    return matrix[:n,:m]
print(top_left_sub_matrix(array,n,m))

array = [[6 4 7 8 6 9 5 5]
 [7 6 7 6 4 1 1 4]
 [1 1 6 8 1 7 5 1]
 [5 8 8 1 3 9 7 6]
 [5 5 8 8 5 6 1 7]
 [7 3 2 5 8 3 1 7]
 [4 7 3 9 5 3 7 2]]
Enter n	2
Enter m	2
[[6 4]
 [7 6]]


### Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the bottom-right N X M sub matrix, e.g:
```
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
```
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are
zero indexed)
```
[
[5, 6]
[8, 9]
]
```


## Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:
[1, 1, 1]
solution(arr) -> should return :
{'mean': 1.0, 'std_dev': 0.0}